---
- name: stop collectd
  service:
    state: stopped
    name: "collectd"
    enabled: no
- name: remove collectd
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ collectd_additional_plugin_list }}"
    - "collectd"
- name: clear collect config
  file: 
    path: "/etc/collectd/"
    state: absent

